apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ui
  labels:
    app: flask-ui
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-ui
  template:
    metadata:
      labels:
        app: flask-ui
    spec:
      imagePullSecrets:
      - name : regcred
      containers:
      - name: flask-ui
        image: vidhis/flask-app:v1
        ports:
        - containerPort: 9595